### PR TITLE
Fix for Specialist Publisher failing make command

### PR DESCRIPTION
**Pull request by Tetrino**
Couldn't run the Make command because of missing updates in the apt-get
library triggering 404 errors. Added an apt-update to make sure it can
grab the needed resources correctly.

### CODE REVIEW

**Review by thomasleese — APPROVED** [review]

**Review by huwd — COMMENTED** [review]
Interesting, why do we think this isn't getting updated with [line 5](https://github.com/alphagov/govuk-docker/blob/aedc90f36e53ea78cd0b23ce4f0c5dd3fabe113a/projects/specialist-publisher/Dockerfile#L5) in this file?

I can't see us adding a source for capybara between there and this line, am i missing something?

**Comment by benthorner** [comment]
> am i missing something?

This is because [the image automatically does an `apt-get clean` after any `apt-get` update](https://github.com/docker-library/buildpack-deps/pull/41). This is evidences by us already having multiple `apt-get update`s.

**Comment by huwd** [comment]
Ah ha, great to know thanks for that link too!

**Review by huwd — APPROVED** [review]
LGTM

**Comment by Tetrino** [comment]
Was away for the best part of a week. Sorry for the delay!

**Pull request merged**
