### PR TITLE
Fix phantomjs not working

### PR DESCRIPTION
**Pull request by benthorner**
This has been causing apps like finder-frontend to fail when running                                                                                                                                                
'rake' or 'rake spec:javascript' since it still uses phantomjs as the 
headless browser, and phantomjs stopped working.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918727

Similar issue: https://github.com/grafana/grafana/issues/17588. 

Looks like the principle way to fix this is to replace PhantomJS!

### CODE REVIEW

**Comment by kevindew** [comment]
This looks good to me, but I'm not too clear what we're actually fixing in govuk-docker with this change? might be good to have that documented in this PR.

**Comment by benthorner** [comment]
@kevindew sure, I've updated the commit/PR. Does that help?

**Comment by issyl0** [comment]
Can we migrate away from PhantomJS in the affected apps?

**Comment by benthorner** [comment]
> Can we migrate away from PhantomJS in the affected apps?

@issyl0 ideally, yes. However, I think that's beyond the scope of this PR. As a compromise, I've pulled back a (not-so-much) 'paid down' tech debt card about this...

https://trello.com/c/M7KeYcSp/83-phantomjs-development-has-been-abandoned

**Comment by benthorner** [comment]
@ChrisBAshton updated with a CHANGELOG alert - would you like to 👀

**Comment by benthorner** [comment]
@ChrisBAshton sure. I didn't realise `1.0.0` signified the 'stable/public' version. To avoid spamming people unduly, I'll increment it here - updated.

**Pull request merged**
